{
  "formatVersion": "1.1",
  "component": {
    "group": "com.convep.qms",
    "module": "qms-plugin",
    "version": "1.17.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qms-plugin-1.17.9.aar",
          "url": "qms-plugin-1.17.9.aar",
          "size": 4109548,
          "sha512": "c4492f02d3f78c18f8d97f022c736c9fb94de38d810db64d7a41f65f4409097bffa6e3a4f86a579e5d91650f24447d635dced1f1e319967e05d8ac7b4b34f858",
          "sha256": "fb58cfa7c83801d2d8b6886e3af102a63a1f3305a30eff24a581cac594f8a2f9",
          "sha1": "5846e5c97964ed6c53b994d7ddf642e59942045d",
          "md5": "a2eeda4b752838a9ee9eafb263b769bf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.facebook.react",
          "module": "react-android",
          "version": {
            "requires": "0.72.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "org.imaginativeworld.whynotimagecarousel",
          "module": "whynotimagecarousel",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.kizitonwose.calendar",
          "module": "view",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.github.mhiew",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "3.2.0-beta.3"
          }
        }
      ],
      "files": [
        {
          "name": "qms-plugin-1.17.9.aar",
          "url": "qms-plugin-1.17.9.aar",
          "size": 4109548,
          "sha512": "c4492f02d3f78c18f8d97f022c736c9fb94de38d810db64d7a41f65f4409097bffa6e3a4f86a579e5d91650f24447d635dced1f1e319967e05d8ac7b4b34f858",
          "sha256": "fb58cfa7c83801d2d8b6886e3af102a63a1f3305a30eff24a581cac594f8a2f9",
          "sha1": "5846e5c97964ed6c53b994d7ddf642e59942045d",
          "md5": "a2eeda4b752838a9ee9eafb263b769bf"
        }
      ]
    }
  ]
}
