{
  "formatVersion": "1.1",
  "component": {
    "group": "com.convep.qms",
    "module": "qms-plugin",
    "version": "1.20.44",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qms-plugin-1.20.44.aar",
          "url": "qms-plugin-1.20.44.aar",
          "size": 4342381,
          "sha512": "d550dbdfb8e668ef5c6227852abcbd93ef16537fd2d762c531563cefc7462e66cb805557146921f3650aab069c36d1e44790182317eebbf10f9d1b0e8744dbb3",
          "sha256": "c5d5761464f7457976a92388ede98eaae69328fbd40d46ab7e57a2f763018c6b",
          "sha1": "2f5ad7584d1ba968e7cd30e99554936e720e24e9",
          "md5": "664c0785619da48777419f2ac52a23a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.facebook.react",
          "module": "react-android",
          "version": {
            "requires": "0.72.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "org.imaginativeworld.whynotimagecarousel",
          "module": "whynotimagecarousel",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.kizitonwose.calendar",
          "module": "view",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.github.mhiew",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "3.2.0-beta.3"
          }
        }
      ],
      "files": [
        {
          "name": "qms-plugin-1.20.44.aar",
          "url": "qms-plugin-1.20.44.aar",
          "size": 4342381,
          "sha512": "d550dbdfb8e668ef5c6227852abcbd93ef16537fd2d762c531563cefc7462e66cb805557146921f3650aab069c36d1e44790182317eebbf10f9d1b0e8744dbb3",
          "sha256": "c5d5761464f7457976a92388ede98eaae69328fbd40d46ab7e57a2f763018c6b",
          "sha1": "2f5ad7584d1ba968e7cd30e99554936e720e24e9",
          "md5": "664c0785619da48777419f2ac52a23a4"
        }
      ]
    }
  ]
}
