{
  "formatVersion": "1.1",
  "component": {
    "group": "com.convep.qms",
    "module": "qms-plugin",
    "version": "1.20.88",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "qms-plugin-1.20.88.aar",
          "url": "qms-plugin-1.20.88.aar",
          "size": 4477115,
          "sha512": "f4321a1fc957aac3999a1583f6e39e30ca27cbcee8b430a3c30e74ea3264944eef43b468e277bd6764b476f175e071f737c180e65ad650ccf7c6992ec6d458af",
          "sha256": "6fd9d49dd1078acd1af387cddacff4e0c2c273cfe47b0758b21ebadac7dde2f2",
          "sha1": "3fea1231b9b593a1a5e4f395144d76f385586d96",
          "md5": "b28db7a328f137d1ead2751a235f0200"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.facebook.react",
          "module": "react-android",
          "version": {
            "requires": "0.72.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.github.chrisbanes",
          "module": "PhotoView",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "org.imaginativeworld.whynotimagecarousel",
          "module": "whynotimagecarousel",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "me.relex",
          "module": "circleindicator",
          "version": {
            "requires": "2.1.6"
          }
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "com.kizitonwose.calendar",
          "module": "view",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.github.marain87",
          "module": "AndroidPdfViewer",
          "version": {
            "requires": "3.2.8"
          }
        }
      ],
      "files": [
        {
          "name": "qms-plugin-1.20.88.aar",
          "url": "qms-plugin-1.20.88.aar",
          "size": 4477115,
          "sha512": "f4321a1fc957aac3999a1583f6e39e30ca27cbcee8b430a3c30e74ea3264944eef43b468e277bd6764b476f175e071f737c180e65ad650ccf7c6992ec6d458af",
          "sha256": "6fd9d49dd1078acd1af387cddacff4e0c2c273cfe47b0758b21ebadac7dde2f2",
          "sha1": "3fea1231b9b593a1a5e4f395144d76f385586d96",
          "md5": "b28db7a328f137d1ead2751a235f0200"
        }
      ]
    }
  ]
}
